// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHuZ54kDkVDu2qIPzH7CFZ6799r3UkILc',
    appId: '1:680655234944:web:0d7867df7767e90aab8365',
    messagingSenderId: '680655234944',
    projectId: 'campusmatchuni',
    authDomain: 'campusmatchuni.firebaseapp.com',
    storageBucket: 'campusmatchuni.appspot.com',
    measurementId: 'G-WVQ2BP708Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7DIbUMQp0meEbMJNPBu2e7XCc5OG5LgQ',
    appId: '1:680655234944:android:0e2311173afd52a0ab8365',
    messagingSenderId: '680655234944',
    projectId: 'campusmatchuni',
    storageBucket: 'campusmatchuni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-EYRwLAJTU5sBd9umc9bg0AnNx6B8Rc8',
    appId: '1:680655234944:ios:d567603dbaf489d1ab8365',
    messagingSenderId: '680655234944',
    projectId: 'campusmatchuni',
    storageBucket: 'campusmatchuni.appspot.com',
    iosBundleId: 'com.example.campusmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-EYRwLAJTU5sBd9umc9bg0AnNx6B8Rc8',
    appId: '1:680655234944:ios:d567603dbaf489d1ab8365',
    messagingSenderId: '680655234944',
    projectId: 'campusmatchuni',
    storageBucket: 'campusmatchuni.appspot.com',
    iosBundleId: 'com.example.campusmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHuZ54kDkVDu2qIPzH7CFZ6799r3UkILc',
    appId: '1:680655234944:web:37c497854f847998ab8365',
    messagingSenderId: '680655234944',
    projectId: 'campusmatchuni',
    authDomain: 'campusmatchuni.firebaseapp.com',
    storageBucket: 'campusmatchuni.appspot.com',
    measurementId: 'G-K048W5L9B4',
  );

}